{
 "title": "EnviroPi Prometheus",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Temperature",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "(temperature * 1.8) + 32", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Humidity",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "humidity", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "NH3",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "kohm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nh3", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "PM 1",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pm1", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Pressure",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pressure", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Light",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 15, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "lux" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "light", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Reduced",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "kohm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "reduced", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "PM 2.5",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pm25", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Oxidised",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "kohm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "oxidised", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "PM 10",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pm10", "legendFormat": "{{instance}}" }
   ]
  }
 ]
}